### PR TITLE
update docker installation tutorial and deeptrader result

### PR DESCRIPTION
**Pull request by qinmoelei**

### CODE REVIEW

**Comment by ai-gamer** [comment]
Please delete irrelevant .pth network files.

**Comment by qinmoelei** [comment]
delete models

**Comment by qinmoelei** [comment]
delete models and update docker tutorial

**Comment by qinmoelei** [comment]
delete models and update docker tutorial

**Comment by qinmoelei** [comment]
delete pyc

**Review by ai-gamer — APPROVED** [review]
Approve

**Pull request merged**
